### ISSUE TITLE
A new mounting system that allows non-leadable mobs

### ISSUE THREAD

**Issue by SuspiciousMango** [TeamOpenIndustry/ImmersiveRailroading#344] opened 2018-06-24 00:43 UTC
I would love to be able to ship creepers, zombies, or Jurassicraft T-Rexes by train, but these mobs are all non-leadable. Is it possible to get a mounting system that does not require the mob to be leaded?

**Comment by cam72cam** [comment] 2021-07-26 12:48
Related to https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/344

**Comment by cam72cam** [comment] 2023-09-14 19:21
Closing as dupe of https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/254

**Closed by cam72cam** 2023-09-14 19:21 UTC
Labels: suggestion
