### ISSUE TITLE
SUGGESTION random wood sleepers for more realistic track

### ISSUE THREAD

**Issue by MrDeathKMGamer** [TeamOpenIndustry/ImmersiveRailroading#1342] opened 2023-02-06 16:12 UTC
well i was think to have random track layout like instend of being one block same track 10 block or more random model
 what do u think about that

**Comment by cam72cam** [comment] 2023-09-14 17:45
Closing as duplicate of https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/1197

**Closed by cam72cam** 2023-09-14 17:45 UTC
Labels: suggestion
