### ISSUE TITLE
[1.16.5] Speed Retardant does not seem to do anything

### ISSUE THREAD

**Issue by umbranium** [TeamOpenIndustry/ImmersiveRailroading#954] opened 2021-04-01 23:25 UTC
**Describe the bug**  
The speed retardant rail augment does not seem to have any effect on the train passing overhead

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Place down a rail
 2. Put a retardant augment on it and power it with redstone
 3. Roll a train over it (no throttle)
 
**Expected behavior**  
 The train would stop or at least slow down

**Screenshots**  
N/A

**System Information**  
Windows
 <br>System Memory: 32gb
 <br>Allocated Memory: 8gb
 <br>CPU: Ryzen 7 3700x
 <br>GPU: GTX 1080 Ti
 <br>IR-Version: 1.16.4-forge-1.8.0.1
 <br>Forge-Version: forge-1.16.5-36.1.0

**Modlist**  
https://i.imgur.com/CHD1Dnr.png
 
**latest.log**
https://drive.google.com/file/d/1rvx0tmTmdPkQDeGyQVXsJkM2okRfrz0H/view?usp=sharing (pastebin limit exceeded)

**Additional context**  
Possible duplicate of: https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/926

**Comment by cam72cam** [comment] 2021-08-01 11:22
Dupe of https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/926

**Closed by cam72cam** 2021-08-01 11:22 UTC
Labels: bug
