### ISSUE TITLE
People Randomly TPing to into train

### ISSUE THREAD

**Issue by N0VVAH** [TeamOpenIndustry/ImmersiveRailroading#853] opened 2020-10-27 19:38 UTC
**Describe the bug**  
When either entering / leaving a train or building a train a person on the server will randomly teleport in to the train. This is seemingly random, usually happens about 1 in 10 times.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. build train
 2. enter and leave repeat ably
 3. Some will teleport in to the train eventually.
 
**Expected behavior**  
 A person not to TP in to the train

**Screenshots**  

**System Information**  
 OS: Linux
 <br>System Memory: Unknown using server host
 <br>Allocated Memory: 7.5GB
 <br>CPU: AMD Ryzen R9 3900X
 <br>GPU: Unknown
 <br>IR-Version: ImmersiveRailroading-1.7.3_1.12.2.jar
 <br>Forge-Version: 1.12.2 - 14.23.5.2854

**Modlist**  
https://pastebin.com/hbRz9WUP
 
**latest.log**
https://pastebin.com/XN8eJvas

**debug.log**
https://pastebin.com/cWnWBx6Q

**Additional context**  
The Logs isn't much use as says nothing but it happened right as '[20:20:06] [Server thread/INFO] [FTB Utilities]: Cam_Archer is no longer AFK' is written

**Comment by km00700** [comment] 2020-10-27 19:40
Duplicate of [](https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/811)

**Closed by km00700** 2020-10-27 19:40 UTC
Labels: bug
