### ISSUE TITLE
Water, clouds rendering bugs caused by IR rails on 1.16

### ISSUE THREAD

**Issue by Vodulm** [TeamOpenIndustry/ImmersiveRailroading#923] opened 2021-02-01 03:01 UTC
... It  only happens if IR rails are exists withing loaded\rendered area.
Didnt noticed anything like this on Mc 1.12.2.

https://vimeo.com/506910278
https://vimeo.com/506910145

**System Information**  
 OS: Windows 10
 <br>System Memory: 8 gb
 <br>Allocated Memory: 2 gb
 <br>CPU: Intel i7-3720QM
 <br>GPU: Nvidia geforce gt 650m
 <br>IR-Version: 1.8.0.1
 <br>Forge-Version: 1.16.4-forge-35.1.37

**Modlist**  

![Capture](https://user-images.githubusercontent.com/73194834/106409701-d55d8c00-6449-11eb-876c-0eea6494bb77.PNG)

**latest.log**
[2021-01-28-8.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/5901620/2021-01-28-8.log)

**Comment by biauk** [comment] 2021-02-01 16:26
I have the same problem.

**Comment by biauk** [comment] 2021-02-07 16:52
It also happens to stained glass.

**Comment by cam72cam** [comment] 2023-09-14 19:05
Closing as dupe of https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/998

**Closed by cam72cam** 2023-09-14 19:05 UTC
Labels: bug
