### ISSUE TITLE
Locomotives/Wagons Dissapearing at high speeds or in general

### ISSUE THREAD

**Issue by RobertX45** [TeamOpenIndustry/ImmersiveRailroading#717] opened 2020-01-02 08:28 UTC
Bug happens when going at high speeds or just randomly with all vehicles in the mod. 

Sometimes it doesnt happen when you place a locomotive or wagon down but if you place another one it happens.

Some are worse than others, completely dissapearing permanently

System:

AMD Ryzen 5 3600 3.6GHz
16GB RAM DDR4
512GB SSD
RX 5700 8GB GDDR6

https://youtu.be/_lUWbB9titU

**Comment by andrboot** [comment] 2020-01-02 21:10
That is a known issue with the current rendering, which is in development.
From Discord FAQ - 
You can't fix that. As of the latest version (1.7.2) the new rendering system just isn't perfect.

**Comment by neronakoma** [comment] 2020-01-03 08:16
due to the way minecraft keeps track of all objects in the game, it is hard to keep a train loaded in at all times and for the server to register where the item is. minecraft uses ticks per second to tell where objects are, the time, and do the calculations needed to make the game operate. all of this loaded down over time will cause certain things to "skip" around. traincraft is a good example of this

**Comment by cam72cam** [comment] 2020-01-12 15:08
@neronakoma that's incredibly incorrect.

This is a dupe of https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/704

**Closed by cam72cam** 2020-01-12 15:08 UTC
Labels: bug
