### ISSUE TITLE
Server Console Error Spam

### ISSUE THREAD

**Issue by OGForlorn** [TeamOpenIndustry/ImmersiveRailroading#813] opened 2020-06-16 03:09 UTC
I'm using ImmersiveRailroading-1.7.3_1.12.2 on a server. The server spams these error's multiple times a second.

[23:02:14] [Server thread/WARN] [net.minecraft.tileentity.TileEntity]: Skipping BlockEntity with id 
[23:02:14] [Server thread/WARN] [universalmodcore]: BAD TE DATA {controlMode:0,parent:{X:0,Y:0,Z:8},railHeight:0.0f,flexible:0b,snowLayers:0,couplerMode:0,version:3,redstoneMode:0,height:0.0f}

This fills up my logs and makes them multiple gigabytes big.

**Comment by septer99** [comment] 2020-08-06 22:21
This can also be caused by the trafficcontrol mod, this is something I've had experience with.

**Comment by andrboot** [comment] 2020-08-15 00:30
This is known, the BAD TE DATA is pending an update release and has been patched.

**Comment by cam72cam** [comment] 2020-11-06 12:05
Fixed in the test-builds, will be in the next release.

**Closed by cam72cam** 2020-11-06 12:05 UTC
Labels: bug
