### ISSUE TITLE
[Suggestion] Railway Buffers.

### ISSUE THREAD

**Issue by Carvercarver1** [TeamOpenIndustry/ImmersiveRailroading#712] opened 2019-12-19 23:29 UTC
Self-explainatory. It has been mentioned here multiple times already. 

It is not fully immersive without this very important feature. I'm even surprised you did not make that one already. 
Also it will be more convinient: you don't have to worry about derailing or accidently destroying certain blocks. Also makes the process of "parking" less annoying and less stressful. Currently, you have to watch it VERY carefully, otherwise you will have a collapsable train, or you may break a few crucial blocks in case of tight spaces. 
Also it will mean that making looped tracks is not an obligation anymore, and will allow more creativity. Because  those are the only option which allows you to avoid raming the wall or so.

It can act as a proxy unmovvable train at the end of the track (it will be "buffer" track type with a buffer at the end), which would stop any incoming train, but would not connect to it or move itself. And it will not be destroyed unless the speed of the train is exceeding 80 km/h.

![image](https://user-images.githubusercontent.com/48799631/71217706-4cc47080-22c7-11ea-8c56-26e22ef5d4af.png)
![image](https://user-images.githubusercontent.com/48799631/71217716-551cab80-22c7-11ea-87ff-6dd8fc063986.png)
![image](https://user-images.githubusercontent.com/48799631/71217738-6a91d580-22c7-11ea-8612-33096fd6232b.png)

**Comment by Larky2k** [comment] 2019-12-19 23:31
planned, at the moment people in RP have add track types that have buffers but don't do anything

**Comment by Carvercarver1** [comment] 2019-12-19 23:34
Oh, that's nice. Any more immersie features planned?

**Comment by km00700** [comment] 2019-12-19 23:36
Check the To-do lists under the Github projects tab. Also, this mod isn't designed to be 100% realistic. The "Immersive" in the name comes from the fact it started as an add-on for the "Immersive Engineering" mod.

**Comment by Carvercarver1** [comment] 2019-12-19 23:38
Got it. 

By the way, can you add a list of "leash" items to config? I tested cargo cars with chains from Ice And Fire, and they don't seem to work altrough they do work like a leash. Only with vanilla one. Or not possible due to limitations?

**Comment by APCBoston** [comment] 2020-01-03 12:31
Just a thought, it might be fun if the bouncy part of the buffer was made from Immersive Engineering jump cushions (for the IE version of the recipe anyway).

**Comment by cam72cam** [comment] 2020-01-12 14:15
Closing as dupe of https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/625

**Closed by cam72cam** 2020-01-12 14:15 UTC
