### ISSUE TITLE
Players are randomly teleported to trains

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [TeamOpenIndustry/ImmersiveRailroading#744] opened 2020-02-22 16:07 UTC
(Running on Dedicated Server)
**Describe the bug**  
Sometimes, when someone is interacting with a train, a seemingly random other player on the server will be teleported to and start riding the train.

**How to reproduce**  
Not easily reproducible, as it seems to be random.
It just happens sometimes when I board or interact with a train
 
**Expected behavior**  
The other player should remain where they are.

**System Information**  
 OS: Windows
 <br>System Memory: 32gb
 <br>Allocated Memory: 16gb
 <br>CPU: AMD Ryzen 9 3900X
 <br>GPU: Unknown, but it's on a server, so it shouldn't matter
 <br>IR-Version: 1.7.2_1.12.2
 <br>Forge-Version: 1.12.2 - 14.23.5.2847

**Modlist**  
[https://hastebin.com/hogosezebe.coffeescript](https://hastebin.com/hogosezebe.coffeescript)
Appearently a mod list is coffee script...
 
**latest.log**
Too large for pastebin, so google drive:
[https://drive.google.com/file/d/1zNQQpW3fcy000AnBlamT4mJD7vvs-96i/view?usp=sharing](https://drive.google.com/file/d/1zNQQpW3fcy000AnBlamT4mJD7vvs-96i/view?usp=sharing)

**Additional context**  
The rails I'm working on are around 15,000 blocks from spawn
Everyone who's been teleported to them has been thousands of blocks away from me, some near spawn, some further away.
Perhaps a simple solution would be to limit how far away you can board a train?
#722 May be related

**Comment by cam72cam** [comment] 2020-04-10 10:47
Yup this is a dupe of: https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/722

**Closed by cam72cam** 2020-04-10 10:47 UTC
Labels: bug
