### ISSUE TITLE
Broken 1m-long tracks. 

### ISSUE THREAD

**Issue by Rysiek18** [TeamOpenIndustry/ImmersiveRailroading#723] opened 2020-01-11 10:28 UTC
**Describe the bug**  
1m-long track behave really weird. They can not face properly anymore, and their look is kind of bizzare

![81645719_509003749736060_7123810878029299712_n](https://user-images.githubusercontent.com/59761804/72202877-d39ee000-3464-11ea-9d54-e889736a2dca.png)

**Comment by cam72cam** [comment] 2020-01-12 13:26
Duplicate of https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/684

**Closed by cam72cam** 2020-01-12 13:26 UTC
Labels: bug
