### ISSUE TITLE
Infinite Speed Boost

### ISSUE THREAD

**Issue by Raeffi** [TeamOpenIndustry/ImmersiveRailroading#835] opened 2020-08-18 12:46 UTC
**Describe the bug**  
Trains gain velocity when going down on a long slope and up on a short one.
**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Go build this:
![2020-08-18_14 15 42](https://user-images.githubusercontent.com/25285430/90514619-b1d7ab00-e161-11ea-8757-fca9eb1921b8.png)
 2. Drive a train down the long slope so it is able to climb the short one at least once and then turn off the engine
 3. Watch the speed increase every loop
 
**Expected behavior**  
 For me (modified slope climbing value) the train gains a few km/h every loop.

**Screenshots**  

![2020-08-18_14 17 19](https://user-images.githubusercontent.com/25285430/90512687-cebeaf00-e15e-11ea-981f-9b386ee6e322.png)
![2020-08-18_14 15 42](https://user-images.githubusercontent.com/25285430/90514619-b1d7ab00-e161-11ea-8757-fca9eb1921b8.png)

**Comment by cam72cam** [comment] 2020-10-19 23:45
Can't reproduce on "reasonable" slopes, closing.

**Closed by cam72cam** 2020-10-19 23:45 UTC
Labels: bug
