### ISSUE TITLE
Bunker & Tank support for Tank Engines

### ISSUE THREAD

**Issue by Glawowow** [TeamOpenIndustry/ImmersiveRailroading#1322] opened 2023-01-07 01:34 UTC
An extra coal storage space in locomotives marked with a Tank Engine section in the JSON. This extra space would behave like a tender, automatically refilling the firebox. There would be a similar setup for water as well, feeding water into the boiler like a tender would. This would allow for much more realistic-behaving tank engines, as currently they run out of coal and water much too quickly compared to how they would IRL.

**Comment by cam72cam** [comment] 2023-09-14 17:58
Closing as dupe of https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/1200

**Closed by cam72cam** 2023-09-14 17:58 UTC
