### ISSUE TITLE
Turntables have no fill texture from above

### ISSUE THREAD

**Issue by Bellpiper** [TeamOpenIndustry/ImmersiveRailroading#938] opened 2021-02-18 02:02 UTC
**Describe the bug**  
When spawning or creating a turntable, the preview shows the turntable has its textures filled beneath the rail. Actually spawning the rail only produces textures on the edge 'ring' of the turntable, and oddly enough the underside. Replacing the block does nothing, and this occurs both in singleplayer and multiplayer.

**How to reproduce**  
Steps to reproduce the unwanted behavior:
1. Build or spawn turntable of any size
2. Profit.
 
**Expected behavior**  
Turntable spawns in with fill beneath rails.

**Screenshots**  
https://pasteboard.co/JOR7Shr.png
https://pasteboard.co/JOR88FW.png

**System Information**  
 OS: win10
 <br>System Memory: 16gb
 <br>Allocated Memory: 2gb
 <br>CPU: "Intel I7 4790k"]
 <br>GPU: MSI GTX 1070
 <br>IR-Version: 1.16.4
 <br>Forge-Version: 1.16.4/1.16.5

**Modlist**  
Create, TrackAPI, Immersive Railroading, Immersive Engineering, Universal Modcore, JEI
 

**Additional context**  
Not sure if this is a trackAPI bug or Immersive railroading.

**Comment by Larky2k** [comment] 2021-02-18 23:33
know issue

**Comment by Larky2k** [comment] 2021-10-08 17:07
> Can confirm that this is happening on my PC as well (AMD Ryzen 5 5600X & 16 GB RAM; GeForce GTX 1050Ti)
know bug regardless of system pointed out when IR went to 1.16 while testing

**Comment by cam72cam** [comment] 2023-09-14 19:04
Closing as dupe of https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/1057

**Closed by cam72cam** 2023-09-14 19:04 UTC
Labels: bug
