### ISSUE TITLE
Custom tracks not spacing properly

### ISSUE THREAD

**Issue by SteampsonJake** [TeamOpenIndustry/ImmersiveRailroading#1345] opened 2023-02-24 21:23 UTC
I've modelled a 1m section of 750mm gauge track and defined the gauge in the json

![image](https://user-images.githubusercontent.com/47562841/221294127-266acef6-2a28-46c5-8f46-d20cffe1c3c9.png)
![image](https://user-images.githubusercontent.com/47562841/221294575-ff6e0329-15e7-4d1e-9803-849d081033b3.png)

When I later placed it in the world with the matching gauge selected, the scale is good, but the individual parts aren't spaced out correctly, creating big overlaps (They're spaced out as if the original model was still 1m of 1435mm track; placed above for comparison)

![2023-02-24_19 26 57](https://user-images.githubusercontent.com/47562841/221295320-7f7a3020-293d-4b3a-969d-b2f34aa1fd2e.png)

**Comment by SteampsonJake** [comment] 2023-02-25 17:04
Made some better visuals for what I mean
How it should be:

![image](https://user-images.githubusercontent.com/47562841/221369927-7f207cc3-8890-490e-b040-e3593bde4f53.png)

And how it actually looks like:

![2023-02-25_18 00 14](https://user-images.githubusercontent.com/47562841/221369950-fa97894a-f32f-4e85-a3c0-ed1ff12e46cb.png)

**Comment by Larky2k** [comment] 2023-02-25 17:20
Not a bug just how IR has been from the very beginning. Do agree it should copy the next one after each other rather than halfway or give an option to choose

**Comment by SteampsonJake** [comment] 2023-02-25 17:24
Why even give the option for custom gauges in the json when you still have to adhere to the "1m of standard gauge track" nonsense? Wasn't the whole point of this to give modelers more flexibility?

**Comment by Larky2k** [comment] 2023-02-25 17:49
The flexibility was so you didn't have to do the nonsense of making it SG for it to scale back down.

**Comment by SteampsonJake** [comment] 2023-02-25 17:52
Well yes, but now I have to make the tracks 750/1435 (or 0.5226) meters long for them to space correctly.

**Comment by cam72cam** [comment] 2023-09-14 17:42
Fixed in the next test build

**Closed by cam72cam** 2023-09-14 17:42 UTC
Labels: bug
