### ISSUE TITLE
Emergency/Decouple brake application

### ISSUE THREAD

**Issue by sjennison** [TeamOpenIndustry/ImmersiveRailroading#1116] opened 2021-11-15 07:35 UTC
It would be nice if upon decoupling, brakes were applied in an emergency/broken air line fashion. Occasionally trains will separate, either because of poor track setup or lag, and it would be nice if brakes were immediately applied and the train stopped (few things are more frustrating than finishing a 40 minute long trip and realizing you left half the train somewhere between the start and the end!). As a bonus, it's realistic too!

**Comment by cam72cam** [comment] 2023-09-14 19:20
Closing as dupe of https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/363

**Closed by cam72cam** 2023-09-14 19:20 UTC
Labels: suggestion, ready to implement
