### ISSUE TITLE
[1.14.4] [Forge] Crash on startup with Botania

### ISSUE THREAD

**Issue by ToMe25** [TeamOpenIndustry/ImmersiveRailroading#753] opened 2020-03-29 09:12 UTC
# Version Information
Minecraft 1.14.4
Forge 28.2.3/28.2.1/28.2.0
Track API 1.2
Immersive Railroading 1.7.3
Curios 1.0.6.1
Patchouli 1.1-26
Botania r1.11-378

# Further Information
Link to crash log: [latest.log](https://pastebin.com/qp8FEYqB)
Botania Issue: Vazkii/Botania#3227

**Comment by shotbyapony** [comment] 2020-04-03 21:02
This has nothing to do with IR.

**Comment by ToMe25** [comment] 2020-04-04 06:50
Sure?
It didn't happen without it.

**Comment by williewillus** [comment] 2020-04-05 04:52
This is almost definitely (99%) not a botania issue. Botania's rendering needs are *dead simple* in comparison to IR and our log is clean on startup, modulo some json texture errors which are benign under forge and botania alone (and I suspect to be caused by other forge bugs).

IR spams the log with tons of texture and model errors even when loading alone. I would bet if those were fixed, this issue would also be fixed. I suspect forge may have buggy error handling that causes errors earlier during model loading to put the model registry in an inconsistent state. When Botania queries the registry to get some models it needs it then blows up (what you see in GunModel at the bottom)

In short, nothing I can do.

**Comment by cam72cam** [comment] 2020-04-05 10:53
@williewillus what's the story behind https://github.com/Vazkii/Botania/commit/76f116dc90b705bd7ada72aaec538fd4fbc51cd6 ?

**Comment by cam72cam** [comment] 2020-04-05 11:33
@williewillus I think I found the problem.  I was accessing the resource manager before it was properly initialized and it may have borked something internal to forge.  When I moved stuff from Setup to Init, it seemed to solve the problem: https://github.com/TeamOpenIndustry/UniversalModCore/commit/4bbeaaf41d0a0d26ac7ced3f99e0ac04116ce765

**Comment by cam72cam** [comment] 2020-04-05 11:50
@ToMe25 try the forge jar in https://github.com/TeamOpenIndustry/ImmersiveRailroading/suites/573944317/artifacts/3894247

**Comment by ToMe25** [comment] 2020-04-05 14:03
Thanks, the Crash is fixed with that versions, i will close this Issue once a build of that is on curseforge :)

**Comment by williewillus** [comment] 2020-04-05 16:30
@cam72cam Forge keeps on loading for some reason even though critical errors have happened early in startup. We were getting lots of crash reports where our ModelBakeEvent was seemingly implicated when it was just the fact that the model registry had not loaded fully due to an earlier error from another mod. So that was added to just skip our ModelBakeEvent handler if our ModelRegistryEvent handler did not get called. Still not foolproof though.

Anyhow, glad the issue has been resolved.

**Comment by cam72cam** [comment] 2020-11-06 12:28
Fixed in the latest test build, will be included in the next release.

**Closed by cam72cam** 2020-11-06 12:28 UTC
