### ISSUE TITLE
No movement using locomotive.

### ISSUE THREAD

**Issue by THASSELHOFF** [TeamOpenIndustry/ImmersiveRailroading#771] opened 2020-04-11 14:59 UTC
Running a 1.12.2 Server with a good handful of mods.
On my singleplayer client I have no issues with the same modpack so I'm sure it isn't a conflict.

On the server:
Placed locomotive whether Steam or Diesel will not move with throttle position. Animations and sounds play without issue but the locomotive will not move in either direction.
Alternatively, the handcar will move but will not carry me with it. When I get out I either teleport to the location it stopped or I drop where I started having not moved.

If a locomotive is placed, however, it will also prevent other players from connecting to the server. When a locomotive is presently loaded, my other player is booted from the session and cannot rejoin. His error is unknown. Just a lost connection.

I do not know how this would be reproduced but my entire reason for running a modded server was to use this mod with my friends and I can't. It's very disappointing.

**Comment by nico7121** [comment] 2020-04-14 14:56
Greetings. Have a similar issue since a few days, might be the same. Could add that the locomotive does seem to move on serverside and in the perspective of other players but not in the perspective of two clients on my server. The issue is not solved by reinstallation of the client. in my case, the locos despawned suddenly and reconnection was possible afterwards.

**Comment by nico7121** [comment] 2020-04-19 19:20
Im not sure if I had a similar Issue on my Server ( but without the connection problems)... Enabling VSync solved the problem (I am not using Optifine btw)

**Comment by km00700** [comment] 2020-04-19 20:15
@THASSELHOFF can you please upload the log file for that server? The player issue sounds like that player doesn't have the resource packs enabled on his client.

**Comment by THASSELHOFF** [comment] 2020-04-22 12:53
@km00700 Sorry, I've been away from my computer. I don't have a log with that issue at the moment and my friend experiencing that issue is doing a new computer build so I won't be able to test again until he finishes in a few days.

**Comment by cam72cam** [comment] 2020-11-06 12:20
Probably a mod conflict, closing with lack of log

**Closed by cam72cam** 2020-11-06 12:20 UTC
Labels: bug
