### ISSUE TITLE
Add textbox on the train

### ISSUE THREAD

**Issue by Excited-Naive** [TeamOpenIndustry/ImmersiveRailroading#576] opened 2019-04-12 16:16 UTC
Use NAME TAG to change the word on the train to name them (like IV mod)

**Comment by Excited-Naive** [comment] 2019-04-12 16:17
Sorry gor submiting a lot of suggestions at the same time.

**Comment by Excited-Naive** [comment] 2019-04-12 16:18
for*

**Comment by km00700** [comment] 2019-04-12 16:21
similar to #30

**Comment by cam72cam** [comment] 2019-10-13 14:54
Closing as dupe of #30

**Closed by cam72cam** 2019-10-13 14:54 UTC
